@echo off
echo Creando entorno virtual...
python -m venv venv
echo Activando entorno virtual...
call venv\Scripts\activate.bat
echo Instalando dependencias...
pip install -r requirements.txt
echo Entorno virtual inicializado exitosamente.
pause
